/**:
    ros__parameters:
        feature_extract_enable: false
        point_filter_num: 3
        max_iteration: 3
        filter_size_surf: 0.1
        filter_size_map: 0.1
        cube_side_length: 1000.0
        runtime_pos_log_enable: false
        map_file_path: "/root/shared_files/dataset/my_map_data/PCD/test.pcd"

        common:
            lid_topic:  "/livox/lidar"
            imu_topic:  "/livox/imu"
            time_sync_en: false
            time_offset_lidar_to_imu: 0.0
            img_topic: "/camera/camera/color/image_raw"
            img_en: 0
            lidar_en: 1
            ros_driver_bug_fix: false

        preprocess:
            lidar_type: 1
            scan_line:  4
            blind: 0.5
            timestamp_unit: 3
            scan_rate: 10

        mapping:
            acc_cov: 0.1
            gyr_cov: 0.1
            b_acc_cov: 0.0001
            b_gyr_cov: 0.0001
            fov_degree:    360.0
            det_range:     100.0
            extrinsic_est_en:  true
            extrinsic_T: [ -0.011, -0.02329, 0.04412 ]
            extrinsic_R: [ 1.0, 0.0, 0.0,
                           0.0, 1.0, 0.0,
                           0.0, 0.0, 1.0] 

        publish:
            path_en: true
            effect_map_en: false
            map_en: true
            scan_publish_en:  true
            dense_publish_en: false
            scan_bodyframe_pub_en: true
            pub_plane_en: false
            pub_scan_num: 1
            blind_rgb_points: 0.0

        pcd_save:
            pcd_save_en: true
            interval: -1
            map_data_path: "/root/shared_files/dataset/my_map_data" 
            colmap_output_en: false
            pcd_save_distance_thresh: 0.2
            filter_size_pcd: 0.1

        extrin_calib:
            Ril: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0] 
            Pil: [-0.011, -0.02329, 0.04412]
            Rcl: [-0.00396865, -0.99998757, -0.00301776,
                  0.00356525, 0.00300362, -0.99998913,
                  0.99998577,-0.00397937, 0.00355329] 
            Pcl: [-0.01998498, -0.07459987, -0.0380765]

        time_offset:
            imu_time_offset: 0.0
            img_time_offset: 0.1
            exposure_time_init: 0.0

        vio:
            max_iterations: 5
            outlier_threshold: 1000.0 
            img_point_cov: 100.0    
            patch_size: 8
            patch_pyrimid_level: 4
            normal_en: true
            raycast_en: false
            inverse_composition_en: false
            exposure_estimate_en: true
            inv_expo_cov: 0.1

        imu:
            imu_en: true
            imu_int_frame: 30
            acc_cov: 0.8
            gyr_cov: 0.5
            b_acc_cov: 0.001
            b_gyr_cov: 0.001

        lio:
            max_iterations: 5
            dept_err: 0.02
            beam_err: 0.15
            min_eigen_value: 0.005
            voxel_size: 0.5
            max_layer: 2
            max_points_num: 50
            layer_init_num: [5, 5, 5, 5, 5]

        local_map:  
            map_sliding_en: false
            half_map_size: 100  
            sliding_thresh: 8.0  

        uav:
            imu_rate_odom: false
            gravity_align_en: false

        evo:
            seq_name: "ishiguro_lab_odom"
            pose_output_en: true

        online_update:
            relocalization_min_feature_num: 10
            keyframe_search_radius: 3.0      
            point_replacement_radius: 0.5

        auto_mode:
            enabled: false
            message_timeout: 5.0